In [1]:
import numpy as np

In [2]:
a = np.array([1,4,5,23,51], dtype='int32')
print(a)

[ 1  4  5 23 51]


In [3]:
b = np.array([[1,43,56,53,12,64],[1,4,5,23,51,23]])
print(b)

[[ 1 43 56 53 12 64]
 [ 1  4  5 23 51 23]]


In [4]:
print("Dimensions:", b.ndim)

Dimensions: 2


In [5]:
print("size:", b.size, "bytes")

size: 12 bytes


In [6]:
print("shape:", b.shape)

shape: (2, 6)


In [7]:
print("type:", b.dtype)

type: int32


In [8]:
print("total size:", b.size*b.itemsize)

total size: 48


In [9]:
print(a.itemsize)
print(b.itemsize)

4
4


In [10]:
print("Total Size:", b.nbytes)

Total Size: 48


## Accesing/Changing 

In [12]:
x = np.array([[1,3,4,5,6],[1,75,34,53,2]])
print(x)

[[ 1  3  4  5  6]
 [ 1 75 34 53  2]]


In [13]:
x[1,1] #[r,c]

75

In [14]:
x[0,:] #Getting specific row

array([1, 3, 4, 5, 6])

In [15]:
x[1,:]

array([ 1, 75, 34, 53,  2])

In [16]:
x[1,0:3]

array([ 1, 75, 34])

In [17]:
x[:,3] #getting specific column

array([ 5, 53])

In [19]:
x[1,2]=30
print(a)

[ 1  4  5 23 51]


In [31]:
a = np.array([[[1,2],[2,3]],[[3,4],[5,6]]])
print(a)

[[[1 2]
  [2 3]]

 [[3 4]
  [5 6]]]


In [35]:
a[:,0,:] #getting specific element

array([[1, 2],
       [3, 4]])

In [36]:
a[:,1,:] #getting specific element

array([[2, 3],
       [5, 6]])

In [37]:
a[:,1,:] = [[2,4],[7,8]] #Replacing the element

In [38]:
print(a)

[[[1 2]
  [2 4]]

 [[3 4]
  [7 8]]]


## Initializing arrays

In [43]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.ones((2,3,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [47]:
np.full((2,2),100)

array([[100, 100],
       [100, 100]])

In [48]:
np.full((3,3),98) #Fill up values

array([[98, 98, 98],
       [98, 98, 98],
       [98, 98, 98]])

In [49]:
np.full((x.shape),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [53]:
np.random.rand(4,2) #Random Decimalnumbers

array([[0.72381668, 0.88006208],
       [0.10971311, 0.70796181],
       [0.25716143, 0.07664738],
       [0.44183936, 0.20867469]])

In [52]:
np.random.random_sample(x.shape) #To fill shape

array([[0.39159625, 0.58038769, 0.95531318, 0.01886136, 0.16446541],
       [0.48543568, 0.01505652, 0.61011043, 0.27179915, 0.82221523]])

In [63]:
np.random.randint(10, size=(3,3)) #Random integer values

array([[8, 5, 9],
       [5, 6, 8],
       [7, 6, 6]])

In [65]:
np.random.randint(5,10, size=(3,3)) #(number or range, size)

array([[9, 9, 6],
       [6, 9, 7],
       [6, 5, 6]])

In [68]:
np.identity(3) #Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
arr = np.array([[1,2,3]]) #To repeat an array
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [78]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Puzzle Problem

In [100]:
q = np.ones((5,5))
print("Initial array: \n",q)

w = np.zeros((3,3))
print("\nSecond array: \n",w)

w[1,1] = 9
print("\n After Changes:\n",w)

Initial array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Second array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 After Changes:
 [[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [101]:
q[1:4,1:4] = w
print("Final Output: \n",q)

Final Output: 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [111]:
p = np.array([1,2,3]) #Careful with Copying Arrays
o = p.copy()
o[0] = 100
print(p)

[1 2 3]


## Mathematics

In [127]:
a1 = np.array([1,2,3])
print(a1)

[1 2 3]


In [128]:
a1 + 2 #adding

array([3, 4, 5])

In [116]:
a1 - 1 #subtracting

array([0, 1, 2])

In [117]:
a1 * 2

array([2, 4, 6])

In [129]:
b1 = np.array([2,2,3])
print(b1)

[2 2 3]


In [130]:
a1 + b1

array([3, 4, 6])

In [131]:
a1 ** 2

array([1, 4, 9])

In [132]:
np.sin(a1) #Sin values

array([0.84147098, 0.90929743, 0.14112001])

In [133]:
np.cos(b1) #cos values

array([-0.41614684, -0.41614684, -0.9899925 ])

## Linear Algebra

In [139]:
a2 = np.ones((2,4)) #Matrix multiplication #no. of col(1st matrix) = no of row (2nd matrix)
b2 = np.full((4,2),3)
print(a2)
print(b2)

np.matmul(a2,b2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]
 [3 3]]


array([[12., 12.],
       [12., 12.]])

In [140]:
c = np.identity(3) #identity matrix
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [141]:
np.linalg.det(c) #Determinant

1.0

In [143]:
l = np.array([[[1,2],[2,3]],[[2,3],[6,7]]])
np.linalg.det(l)

array([-1., -4.])

In [146]:
np.linalg.inv(l) #Inverse matrix

array([[[-3.  ,  2.  ],
        [ 2.  , -1.  ]],

       [[-1.75,  0.75],
        [ 1.5 , -0.5 ]]])

## Statistics

In [168]:
stats = np.array([[1,1,2],[2,3,7]])
print(stats)

[[1 1 2]
 [2 3 7]]


In [169]:
np.min(stats, axis=1) #minimum #axis=1 specifies min of first row and then second row

array([1, 2])

In [170]:
np.max(stats, axis=1) #maximum

array([2, 7])

In [172]:
np.sum(stats , axis =0) #Adding all elements

array([3, 4, 9])

## Reorganizing arrays

In [181]:
before = np.array([[1,4,6,5],[5,4,2,9]])
before

array([[1, 4, 6, 5],
       [5, 4, 2, 9]])

In [182]:
after = before.reshape((8,1)) #reshaping the array
after

array([[1],
       [4],
       [6],
       [5],
       [5],
       [4],
       [2],
       [9]])

In [183]:
after = before.reshape((2,2,2))
after

array([[[1, 4],
        [6, 5]],

       [[5, 4],
        [2, 9]]])

In [186]:
v1 = np.array([1,2,3,4]) #Vetical Stacking
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [190]:
np.hstack([v1,v2,v2,v1,v2]) #Horizontal Stacking

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [193]:
h1 = np.zeros((2,3))
h2 = np.ones((2,4))

np.hstack([h1,h2])

array([[0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.]])

In [199]:
filedata = np.genfromtxt('demo.txt',delimiter=',') #Getting values from text file
filedata

array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.],
       [1., 4., 6., 3., 8.]])

In [202]:
filedata.astype('int32') #to change into integer

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [1, 4, 6, 3, 8]])

In [205]:
filedata > 5 

array([[False, False, False, False, False],
       [ True,  True,  True,  True, False],
       [False, False,  True, False,  True]])

In [207]:
filedata[filedata > 5] #Getting values greater than 5

array([6., 7., 8., 9., 6., 8.])

In [209]:
a4 = np.array([1,2,3,4,5,6]) #getting values from array
a4[[1,3,5]]

array([2, 4, 6])

In [ ]:
a[2:4,0:2]
a[[0,1,2,3],[1,2,3,4]]
a[[0,4,5],3:]